<div id="faq">
    <div class="left-col col-md-3">
        <ul class="navCol-two">
            <li><a href="<?php echo $this->getUrl('lam-the-nao-de-kiem-tra-tinh-trang-don-hang');?>"><span>Giao hàng &amp; Nhận hàng</span></a>
            </li>
            <li><a href="http://www.lazada.vn/helpcenter/returns-refunds/#answer-faq-return-ans"><span>Đổi trả hàng &amp; Hoàn tiền</span></a>
            </li>
            <li><a href="http://www.lazada.vn/helpcenter/orders-payment/#answer-faq-placeorder-ans"><span>Đơn hàng &amp; Thanh toán</span></a>
            </li>
            <li><a href="http://www.lazada.vn/helpcenter/products-on-lazada/#answer-faq-productinfo-ans"><span>Sản phẩm trên website Shopbing</span></a>
            </li>
            <li><a href="http://www.lazada.vn/helpcenter/sellers-on-lazada/?boost=3#answer-faq-sellerinfo-ans"><span>Nhà bán hàng trên website Shopbing</span></a>
            </li>
            <li><a href="http://www.lazada.vn/helpcenter/vouchers-promotions/#answer-faq-voucher-ans"><span>Mã giảm giá &amp; Khuyến mãi</span></a>
            </li>
            <li><a href="http://www.lazada.vn/helpcenter/your-account/#answer-faq-manageaccount-ans"><span>Tài khoản mua hàng</span></a>
            </li>
            <li><a href="http://www.lazada.vn/helpcenter/marketplace/#answer-faq-marketplace-ans"><span>Đơn hàng Thương nhân thành viên</span></a>
            </li>
            <!--li><a href="http://www.lazada.vn/helpcenter/contact-us/#answer-faq-contactus-ans"><span>Liên hệ</span></a></li-->
            <!--li><a href="http://www.lazada.vn/helpcenter/information/#answer-faq-information-ans"><span>Thông tin</span></a></li-->
            <div class="contact-box">
                <div class="contact-title">Quý khách không thể tìm thấy câu trả lời cần tìm?</div>
                <a class="contact-btn" href="<?php echo Mage::getUrl('contacts');?>">
                    <span class="btn btn-warning btn-block">Nhấn vào đây</span>
                    <span class="btn-icon"></span> </a>
            </div>
        </ul>
    </div>
    <div class="right-col col-md-9">

        <!-- Most FAQ - 10 most asked questions -->

        <div id="faq-mostfaq-sub" class="current">
            <div class="common-question">
                <div class="left-col1">
                    <a href="http://www.lazada.vn/helpcenter/shipping-delivery/#answer-faq-delivery-ans">
                        <span class="faq-icon question1">
                        <span class="fa fa-calendar fa-5x" aria-hidden="true"></span>
                        </span>
                        <span class="question-title">Khi nào tôi nhận được đơn hàng ?</span> </a>

                    <a href="http://www.lazada.vn/helpcenter/shipping-delivery/#answer-faq-trackorder-ans">
                        <span class="faq-icon question2">
                        <span class="fa fa-paper-plane fa-5x"></span>
                        </span>
                        <span class="question-title">Làm thế nào để tôi kiểm tra tình trạng đơn hàng của tôi?</span>
                    </a>
                    <a href="http://www.lazada.vn/helpcenter/orders-payment/#answer-faq-changeorder-ans">
                        <span class="faq-icon question3">
                        <span class="fa fa-trash fa-5x"></span>
                        </span>
                        <span class="question-title">Làm thế nào để hủy đơn hàng?</span> </a>
                    <a href="http://www.lazada.vn/helpcenter/returns-refunds/#answer-faq-return-ans">
                        <span class="faq-icon question4">
                        <span class="fa fa-exchange fa-5x"></span>
                        </span>
                        <span class="question-title">Làm thế nào để đổi trả sản phẩm?</span> </a>
                    <a href="http://www.lazada.vn/helpcenter/shipping-delivery/#answer-faq-delivery-ans_faq-multipleitems-ans">
                        <span class="faq-icon question5">
                            <img style="width: 100px; margin-top: 20px;" src="<?php echo Mage::getDesign()->getSkinUrl('images/products-icon.png');?>"/>
                        </span>
                        <span class="question-title">Tôi đặt nhiều sản phẩm, nhưng chỉ nhận được một, vậy các sản phẩm còn lại của tôi đâu?</span>
                    </a>
                    <a href="http://www.lazada.vn/helpcenter/orders-payment/#answer-faq-payment-ans">
                        <span class="faq-icon question6">
                            <span class="fa fa-credit-card fa-5x"></span>
                        </span>
                        <span class="question-title">Các hình thức thanh toán đang được áp dụng là gì?</span> </a>
                    <a href="http://www.lazada.vn/helpcenter/orders-payment/#answer-faq-payment-ans_faq-paymentnotification-ans">
                        <span class="faq-icon question7">
                            <span class="fa fa-credit-card-alt fa-5x"></span>
                        </span>
                        <span class="question-title">Làm thế nào để biết giao dịch thanh toán của tôi có thành công hay không ?</span>
                    </a>
                    <a href="http://www.lazada.vn/helpcenter/shipping-delivery/#answer-faq-shippingfee-ans">
                        <span class="faq-icon question8">
                            <span class="fa fa fa-truck fa-5x"></span>
                        </span>
                        <span class="question-title">Phí vận chuyển và phí cồng kềnh là gì?</span> </a>
                    <a href="http://www.lazada.vn/helpcenter/products-on-lazada/#answer-faq-productinfo-ans">
                        <span class="faq-icon question9">
                            <span class="fa fa-info-circle fa-5x"></span>
                        </span>
                        <span class="question-title">Tôi có thể xem thêm thông tin về sản phẩm ở đâu?</span> </a>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>