<div class="right1-group">	
	<div class="row">
		<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
			<?php  echo $this->getLayout()->createBlock('producttabs/producttabs')->setTemplate('magentothem/producttabs/producttabs.phtml')->toHtml(); ?>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
			<?php  echo $this->getLayout()->createBlock('testimonial/sidebar')->setTemplate('magentothem/testimonial/sidebar/slider.phtml')->toHtml(); ?>
		</div>
	</div>
</div>