<div class="top-group">
	<div class="row">
		<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
			<?php  echo $this->getLayout()->createBlock('vmegamenu/vmegamenu')->setTemplate('magentothem/vmegamenu/vmegamenu.phtml')->toHtml(); ?>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<?php
				$block = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('static_top');
				echo Mage::getSingleton('widget/template_filter')->filter($block->getContent());
			?>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
			<?php
				$block = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('corporate');
				echo Mage::getSingleton('widget/template_filter')->filter($block->getContent());
			?>
		</div>
	</div>
</div>

