<div class="seller-container">
    <div id="seller-list">
        <div data-reactroot="">
            <div class="current-seller" data-id="1">
                <div class="title">
                    <div class="img"></div>
                    <div class="text">Cung cấp bởi<br>
                        <span>Shopsbing.xyz</span>
                    </div>
                </div>
                <ul class="seller-feature">
                    <li><span class="icon warranty-icon"></span>
                        <div class="content"><span class="title">Hình thức bảo hành</span><b>Hóa đơn</b></div>
                    </li>
                    <li><span class="icon warranty-lifetime-icon"></span>
                        <div class="content"><span class="title">Thời gian bảo hành</span><b>12 tháng chính hãng tại Asus Việt Nam</b></div></li>
                    <li><span class="icon hotline-icon"></span>
                        <div class="content"><span class="title">Liên hệ</span><b>HOTLINE: 1900 6035</b><br>(1.000đ/phút, 8-21h cả T7, CN)</div>
                    </li>
                </ul>
            </div>
            <div class="other-seller" style="display: none;"><p>TỪ NHÀ CUNG CẤP KHÁC</p><ul id="otherSellerList" class="other-seller-list "></ul></div>
        </div>
    </div>
    <div class="register-to-sell">
        Bạn muốn bán hàng cùng Tiki? <a target="_blank" href="/ban-hang-cung-tiki?ref=pdp-seller-info">Đăng ký ngay</a>
    </div>
</div>