
<div style="float: left">
<a style="width: 150px;" href="<?php echo Mage::getBaseUrl(). 'checkorder/'?>" title="Kiểm tra trạng thái Đơn hàng của bạn" class="tracking-order item col-md-6 col-xs-6">
    <img style="width: 60px; float: left; margin-right: 5px" class="ico ico-order-tracking" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'wysiwyg/icon/order-tracking-icon.png'?>"/>
    Theo dõi <br/> đơn hàng
</a>
</div>
