<?php
    $_productCollection=$this->getProducts();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="mage-products">
    <?php
	$width = Mage::getStoreConfig('producttabs/producttabs_config/width_thumbnail'); 
	$height = Mage::getStoreConfig('producttabs/producttabs_config/height_thumbnail'); 
    ?>

    <?php $_collectionSize = $_productCollection->count() ?>
	<?php
	$rows = Mage::getStoreConfig('producttabs/producttabs_config/row_show');
	?>
    <ul class="producttabs-products-owl">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
			<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
			<?php if($i %$rows == 0) echo "<li class='item'>"; ?>
				<div class="item_inner">
					<div class="item-content">
						<div class="products">
							<div class="product-image">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								</a>
							</div>
						</div>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php if(Mage::getStoreConfig('producttabs/producttabs_config/review')): ?>
							 <?php
							$storeId = Mage::app()->getStore()->getId();
							$summaryData = Mage::getModel('review/review_summary')
												->setStoreId($storeId)
												->load($_product->getId());
							if ($summaryData['rating_summary']):
							?>
								<div class="ratings">
									<div class="rating-box">  
										<div class="rating" style="width: <?php echo $summaryData['rating_summary'] ; ?>%;"></div>  
									</div>
									<span class="amount"><a onclick="var t = opener ? opener.window : window; t.location.href='<?php echo Mage::getUrl("review/product/list/id/".$_product->getId()) ?>'; return false;" href="#"><?php echo $summaryData['reviews_count'] ?> Review(s)</a></span>
								</div>
							<?php endif; ?>
						<?php endif; ?>
						<?php
							if(Mage::getStoreConfig('producttabs/producttabs_config/show_price')):
						?>
							<div class="price-box">
								<?php
								$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
								$price = $_product->getPrice();
								$specialprice = $_product->getFinalPrice();
								if($price != $specialprice){
								if($price != ''){
								echo '<p class="old-price"><span class="price-label">';
								echo $this->__('Regular Price'). ': </span>';
								echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
								}
								if($specialprice != '')
								{
								echo '<p class="special-price">
								<span class="price-label">Special Price</span>
								<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
								</p> ';
								} 
								}else {
								echo '<div class="price-boxs">
								<span class="regular-price">
								<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
								</span>    
								</div>';    
								}
								?>
							</div>
						<?php endif; ?>
						<div class="actions">
							<div class="actions-inner">
								<?php if(Mage::getStoreConfig('producttabs/producttabs_config/addtocart')):?>
									<?php if($_product->isSaleable()): ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
								<?php endif; ?>
								<ul class="add-to-links">
									<?php if(Mage::getStoreConfig('producttabs/producttabs_config/addtowishlist')):?>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
									<?php endif; ?>
									<?php if(Mage::getStoreConfig('producttabs/producttabs_config/addtocompare')):?>
										<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare "><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
									<?php endif; ?>
								</ul>
							</div>	
						</div>
					</div>
				</div>	
            <?php $i++;?>
			<?php if($i %$rows == 0) echo "</li>"; ?> 
        <?php endforeach; ?>
			<?php if($i %$rows != 0) echo "</li>"; ?>
    </ul>
</div>
<?php endif; ?>
