<div class="slider-group">
	<div class="container">
		<div class="row">
			<div class="col-left col-lg-3 col-md-3 col-sm-12 col-xs-12">
				
			</div>
<!--			<div class="col-right col-lg-9 col-md-9 col-sm-12 col-xs-12">-->
<!--				--><?php // echo $this->getLayout()->createBlock('banner7/banner7')->setTemplate('magentothem/banner7/banner7.phtml')->toHtml(); ?>
<!--			</div>-->
            <div class="col-center col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <?php  echo $this->getLayout()->createBlock('banner7/banner7')->setTemplate('magentothem/banner7/banner7.phtml')->toHtml(); ?>
            </div>
            <div class="col-right col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <?php
                $block = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('static_top2');
                echo Mage::getSingleton('widget/template_filter')->filter($block->getContent());
                ?>
            </div>
		</div>
	</div>
</div>