<div class="module-group">
<div class="container">
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
			<?php  echo $this->getLayout()->createBlock('blog/menu_sidebar')->setTemplate('magentothem_blog/blog_slide.phtml')->toHtml(); ?>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
			<?php  echo $this->getLayout()->createBlock('bestsellerproductslider/bestsellerproductslider')->setTemplate('magentothem/bestsellerproductslider/bestsellerproductslider.phtml')->toHtml(); ?>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
			<?php  echo $this->getLayout()->createBlock('onsaleslider/onsaleslider')->setTemplate('magentothem/onsaleslider/onsaleslider.phtml')->toHtml(); ?>
		</div>
	</div>
</div>
</div>